@startuml
title Simple Uml Diagram For Foods Library (Not all relationships shown)
<style>
title {
  HorizontalAlignment center
  FontSize 24
}
</style>
class java.util.ArrayList<Interface_food>
interface io.github.xjrga.foods.Interface_dri
interface io.github.xjrga.foods.Interface_dri_mutable
interface io.github.xjrga.foods.Interface_food
interface io.github.xjrga.foods.Interface_food_mutable
abstract class io.github.xjrga.foods.Abstract_dri implements io.github.xjrga.foods.Interface_dri
abstract class io.github.xjrga.foods.Abstract_dri implements io.github.xjrga.foods.Interface_dri_mutable
abstract class io.github.xjrga.foods.Abstract_food implements io.github.xjrga.foods.Interface_food
abstract class io.github.xjrga.foods.Abstract_food implements io.github.xjrga.foods.Interface_food_mutable
class io.github.xjrga.foods.Food_mutable implements io.github.xjrga.foods.Interface_food
class io.github.xjrga.foods.Food_mutable implements io.github.xjrga.foods.Interface_food_mutable
class io.github.xjrga.foods.Food_multiplier implements io.github.xjrga.foods.Interface_food
class io.github.xjrga.foods.Food_summator implements io.github.xjrga.foods.Interface_food
class io.github.xjrga.foods.Mangos_raw extends io.github.xjrga.foods.Abstract_food
class io.github.xjrga.foods.Dri_daily_value extends io.github.xjrga.foods.Abstract_dri
io.github.xjrga.foods.Interface_food <.. io.github.xjrga.foods.Food_multiplier
io.github.xjrga.foods.Food_summator ..> java.util.ArrayList 
io.github.xjrga.foods.Coefficient_food ..> java.util.ArrayList 
io.github.xjrga.foods.Coefficient_nutrient ..> java.util.ArrayList
io.github.xjrga.foods.Chef o.. java.util.ArrayList
@enduml