@startuml
title Simple Uml Diagram For Foods Library (Not all relationships shown)
<style>
title {
  HorizontalAlignment center
  FontSize 24
}
</style>
class java.util.ArrayList<Abstract_food>
interface io.github.xjrga.foods.Interface_dri_get
interface io.github.xjrga.foods.Interface_dri_set
interface io.github.xjrga.foods.Interface_food_get
interface io.github.xjrga.foods.Interface_food_set
interface io.github.xjrga.foods.Interface_food_coefficient
abstract class io.github.xjrga.foods.Abstract_dri implements io.github.xjrga.foods.Interface_dri_get
abstract class io.github.xjrga.foods.Abstract_dri implements io.github.xjrga.foods.Interface_dri_set
abstract class io.github.xjrga.foods.Abstract_food implements io.github.xjrga.foods.Interface_food_get
abstract class io.github.xjrga.foods.Abstract_food implements io.github.xjrga.foods.Interface_food_set
abstract class io.github.xjrga.foods.Abstract_food implements io.github.xjrga.foods.Interface_food_coefficient
class io.github.xjrga.foods.Food_data implements io.github.xjrga.foods.Interface_food_get
class io.github.xjrga.foods.Food_data implements io.github.xjrga.foods.Interface_food_set
class io.github.xjrga.foods.Mangos_raw extends io.github.xjrga.foods.Abstract_food
class io.github.xjrga.foods.Dri_daily_value extends io.github.xjrga.foods.Abstract_dri
class io.github.xjrga.foods.Concrete_food extends io.github.xjrga.foods.Abstract_food
class io.github.xjrga.foods.Food_multiply extends io.github.xjrga.foods.Abstract_food
class io.github.xjrga.foods.Food_sum extends io.github.xjrga.foods.Abstract_food
io.github.xjrga.foods.Coefficient_food ..> java.util.ArrayList
io.github.xjrga.foods.Coefficient_nutrient ..> java.util.ArrayList
io.github.xjrga.foods.Concrete_food ..> io.github.xjrga.foods.Food_data
io.github.xjrga.foods.Food_sum ..> java.util.ArrayList
io.github.xjrga.foods.Food_multiply ..> io.github.xjrga.foods.Abstract_food
io.github.xjrga.foods.Chef o.. java.util.ArrayList
@enduml